[package]
name = "bind-parser"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.70.1"

[dependencies]
anyhow = "1.0.90"
lsp-server = "0.7.7"
lsp-types = "0.97.0"
serde = "1.0.210"
serde_json = "1.0.128"

[profile.test]
opt-level = 0
debug = 2
